# Generated by Django 5.0.6 on 2024-05-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Автор рецепта', 'verbose_name_plural': 'Авторы рецептов'},
        ),
    ]
