# Generated by Django 5.0.6 on 2024-05-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Автора рецепта', 'verbose_name_plural': 'Авторы рецептов'},
        ),
    ]
